import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../services/api';
import useInterviewSession from '../hooks/useInterviewSession';
import ScoreRing from '../components/ScoreRing';
import QuestionDetailAccordion from '../components/QuestionDetailAccordion';
import {
  Award, CheckCircle2, AlertTriangle, ShieldCheck, RefreshCw,
  BarChart2, Star, Zap, User, ListChecks,
} from 'lucide-react';

function Dashboard() {
  const session = useInterviewSession();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [expandedId, setExpandedId] = useState(null);
  const navigate = useNavigate();

  useEffect(() => {
    const fetchReport = async () => {
      const sessionId = session.getSessionId();
      if (!sessionId) {
        navigate('/upload');
        return;
      }

      setLoading(true);
      setError(null);

      try {
        const response = await api.getReport(sessionId);
        setReport(response);
      } catch (err) {
        console.error(err);
        setError(err.response?.data?.detail || 'Failed to fetch the performance report.');
      } finally {
        setLoading(false);
      }
    };

    fetchReport();
  }, [navigate, session.getSessionId]);

  const handleRestart = () => {
    session.clearSession();
    navigate('/upload');
  };

  const getScoreRating = (score) => {
    if (score >= 80) return { label: 'Excellent — Ready for Industry', class: 'text-cyber-success' };
    if (score >= 60) return { label: 'Good — Strong Foundations', class: 'text-cyber-warning' };
    return { label: 'Needs Practice — Target Weaknesses', class: 'text-cyber-danger' };
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] gap-4">
        <RefreshCw className="h-10 w-10 text-cyber-primary animate-spin" />
        <span className="text-cyber-muted text-sm font-semibold">Compiling Performance Diagnostics...</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-md mx-auto flex flex-col items-center text-center gap-4 py-12">
        <AlertTriangle className="h-12 w-12 text-cyber-danger" />
        <h3 className="text-xl font-bold">Report Generation Failed</h3>
        <p className="text-cyber-muted text-sm">{error}</p>
        <button onClick={handleRestart} className="btn-primary mt-2">Start New Session</button>
      </div>
    );
  }

  const rating = getScoreRating(report.overall_score);

  return (
    <div className="max-w-5xl mx-auto flex flex-col gap-8 md:gap-12 animate-fade-in pb-16">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div className="flex flex-col gap-2">
          <h2 className="text-3xl font-bold tracking-tight text-white flex items-center gap-3">
            <BarChart2 className="h-8 w-8 text-cyber-primary" /> Performance Report
          </h2>
          <p className="text-cyber-muted">Final analysis generated by Sentence-BERT semantic models.</p>
        </div>
        <button onClick={handleRestart} className="btn-secondary flex items-center justify-center gap-2 py-3 px-6">
          <RefreshCw className="h-4 w-4" /> Start New Session
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="glass-card p-8 rounded-3xl flex flex-col items-center justify-center text-center relative overflow-hidden">
          <ScoreRing score={report.overall_score} label="Overall Score" />
          <span className={`text-xs font-bold mt-4 tracking-wide uppercase ${rating.class}`}>
            {rating.label}
          </span>
        </div>

        <div className="glass-card p-8 rounded-3xl flex flex-col justify-between">
          <div className="flex flex-col gap-3">
            <div className="h-10 w-10 rounded-xl bg-cyber-secondary/15 flex items-center justify-center text-cyber-secondary">
              <Zap className="h-5 w-5" />
            </div>
            <h4 className="text-sm font-semibold text-cyber-muted font-mono uppercase tracking-wider">Technical Capability</h4>
            <p className="text-cyber-muted text-xs leading-relaxed">Keyword coverage, structural correctness, and concept accuracy.</p>
          </div>
          <div className="flex items-baseline gap-1 mt-6">
            <span className="text-4xl font-extrabold text-white">{report.technical_score}</span>
            <span className="text-lg text-cyber-muted">/100</span>
          </div>
        </div>

        <div className="glass-card p-8 rounded-3xl flex flex-col justify-between">
          <div className="flex flex-col gap-3">
            <div className="h-10 w-10 rounded-xl bg-cyber-accent/15 flex items-center justify-center text-cyber-accent">
              <Award className="h-5 w-5" />
            </div>
            <h4 className="text-sm font-semibold text-cyber-muted font-mono uppercase tracking-wider">Semantic Similarity</h4>
            <p className="text-cyber-muted text-xs leading-relaxed">Sentence-BERT embedding cosine similarity vs. reference answers.</p>
          </div>
          <div className="flex items-baseline gap-1 mt-6">
            <span className="text-4xl font-extrabold text-white">{report.average_similarity}</span>
            <span className="text-lg text-cyber-accent font-bold">%</span>
          </div>
        </div>
      </div>

      <div className="glass-card p-6 rounded-2xl flex items-center gap-5 border border-white/5">
        <div className="h-12 w-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center text-cyber-muted shrink-0">
          <User className="h-6 w-6" />
        </div>
        <div className="flex flex-wrap gap-y-2 gap-x-6 text-sm">
          <div className="flex flex-col">
            <span className="text-xs text-cyber-muted font-mono uppercase">Extracted Profile</span>
            <span className="font-semibold text-white truncate max-w-[200px]">
              {report.resume_summary.education?.[0] || 'Resume File'}
            </span>
          </div>
          <div className="flex flex-col">
            <span className="text-xs text-cyber-muted font-mono uppercase">Skills Verified</span>
            <span className="font-semibold text-cyber-primary">
              {report.resume_summary.skills?.slice(0, 3).join(', ') || 'N/A'}
              {report.resume_summary.skills?.length > 3 ? ' ...' : ''}
            </span>
          </div>
          <div className="flex flex-col">
            <span className="text-xs text-cyber-muted font-mono uppercase">Key Projects</span>
            <span className="font-semibold text-cyber-accent">
              {report.resume_summary.projects?.slice(0, 2).join(', ') || 'N/A'}
            </span>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="glass-card p-6 rounded-2xl border-t-4 border-t-cyber-success flex flex-col gap-4">
          <h3 className="font-bold flex items-center gap-2 border-b border-white/5 pb-3">
            <ShieldCheck className="h-5 w-5 text-cyber-success" /> Strengths
          </h3>
          <ul className="flex flex-col gap-4">
            {report.strengths.map((str, i) => (
              <li key={i} className="text-xs leading-relaxed flex items-start gap-2.5">
                <CheckCircle2 className="h-4 w-4 text-cyber-success shrink-0 mt-0.5" />
                <span className="text-cyber-text/90">{str}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="glass-card p-6 rounded-2xl border-t-4 border-t-cyber-warning flex flex-col gap-4">
          <h3 className="font-bold flex items-center gap-2 border-b border-white/5 pb-3">
            <AlertTriangle className="h-5 w-5 text-cyber-warning" /> Conceptual Gaps
          </h3>
          <ul className="flex flex-col gap-4">
            {report.weaknesses.map((wk, i) => (
              <li key={i} className="text-xs leading-relaxed flex items-start gap-2.5">
                <div className="h-1.5 w-1.5 rounded-full bg-cyber-warning shrink-0 mt-2" />
                <span className="text-cyber-text/90">{wk}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="glass-card p-6 rounded-2xl border-t-4 border-t-cyber-primary flex flex-col gap-4">
          <h3 className="font-bold flex items-center gap-2 border-b border-white/5 pb-3">
            <Star className="h-5 w-5 text-cyber-primary" /> Actionable Tips
          </h3>
          <ul className="flex flex-col gap-4">
            {report.suggestions.map((sug, i) => (
              <li key={i} className="text-xs leading-relaxed flex items-start gap-2.5">
                <span className="text-cyber-primary font-bold shrink-0 mt-0.5">•</span>
                <span className="text-cyber-text/90">{sug}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Per-question breakdown */}
      {report.details?.length > 0 && (
        <div className="flex flex-col gap-6">
          <h3 className="text-xl font-bold flex items-center gap-2">
            <ListChecks className="h-5 w-5 text-cyber-primary" />
            Question-by-Question Breakdown
          </h3>
          <div className="flex flex-col gap-4">
            {report.details.map((item) => (
              <QuestionDetailAccordion
                key={item.id}
                question={{ id: item.id, question: item.question, category: item.category, reference_answer: item.reference_answer }}
                candidateAnswer={item.candidate_answer}
                evaluation={{
                  technical_score: item.technical_score,
                  similarity_score: item.similarity_score,
                  reference_answer: item.reference_answer,
                  strengths: item.strengths,
                  weaknesses: item.weaknesses,
                  suggestions: item.suggestions,
                }}
                isExpanded={expandedId === item.id}
                onToggle={() => setExpandedId(expandedId === item.id ? null : item.id)}
              />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default Dashboard;
